@startuml Usecase

left to right direction

actor 利用者

rectangle Web予約 {
    利用者 --> (会員登録する)
    利用者 --> (ログインする)
    利用者 --> (利用日付を選択する)
    利用者 --> (利用スタジオと利用時間枠を選択する)
    利用者 --> (レンタル機材を選択する)
    利用者 --> (予約を確定する)
    利用者 --> (予約をキャンセルする)

    note right of (利用スタジオと利用時間枠を選択する)
    スタジオごとに利用可能時間枠が表示される。
    end note

    note right of (レンタル機材を選択する)
    指定された利用日付の利用時間枠で空いている備品を選択できる。
    end note
    
    note right of (予約を確定する)
    利用日時、利用スタジオ、予約機材、情報を確認して確定する。
    end note
}

@enduml
