@startuml Usecase

left to right direction

actor 利用者

rectangle 会員サイト {
    利用者 --> (会員登録する)
    利用者 --> (会員情報を変更する)
    利用者 --> (退会する)

    note right of (会員登録する)
    メールアドレス、パスワード、名前、電話番号、生年月日を登録する。
    （メールアドレスがログインIDとなる。）
    end note
}

@enduml
