@startuml Usecase

left to right direction

actor 利用者

rectangle 予約サイト {
    利用者 --> (会員登録する)
    利用者 --> (ログインする)

    利用者 --> (予約する)
    (予約する) --> (予約を確定する)
    (予約する) --> (レンタル機材を選択する)
    (予約する) --> (利用スタジオと利用時間枠を選択する)
    (予約する) --> (利用日付を選択する)

    note right of (会員登録する)
    メールアドレス、パスワード、名前、電話番号、生年月日を登録する。
    end note

    note right of (ログインする)
    メールアドレス、パスワードでログインする。
    end note

    note right of (利用スタジオと利用時間枠を選択する)
    スタジオごとに利用可能時間枠が表示される。
    end note

    note right of (レンタル機材を選択する)
    指定された利用日付の利用時間枠で空いている備品を選択できる。
    end note
    
    note right of (予約を確定する)
    利用日時、利用スタジオ、予約機材、情報を確認して確定する。
    end note

    利用者 --> (予約をキャンセルする)
    (予約をキャンセルする) --> (キャンセルする)
    (予約をキャンセルする) --> (キャンセル対象の予約を選択する)

    note right of (予約をキャンセルする)
    キャンセル料がかからない日付ならキャンセル可能。
    キャンセル料がかかってしまう場合は電話でのキャンセルのみ可能。
    end note

    利用者 --> (レンタル機材を変更する)
    (レンタル機材を変更する) --> (変更する)
    (レンタル機材を変更する) --> (変更対象の予約を選択する)
}

@enduml
