@startuml Usecase

left to right direction

actor 利用者
actor スタッフ

利用者 --> スタッフ

note top of スタッフ
利用者から
会員情報や予約内容を
受け付ける。
end note

rectangle 管理サイト {
    スタッフ --> (ログインする)
    スタッフ --> (会員を検索する)
    スタッフ --> (予約する)
    スタッフ --> (予約を変更する)
    スタッフ --> (予約をキャンセルする)

    note right of (会員を検索する)
    利用者から聞いた会員情報で検索する。
    end note

    note right of (予約する)
    会員検索で見つかった会員で予約する。
    見つからなかった場合は非会員として予約する。
    その他入力する情報は Web 予約と同じ。
    end note
}

@enduml
