@startuml Usecase

left to right direction

actor 利用者
actor スタッフ

利用者 --> スタッフ

note top of スタッフ
利用者から以下の情報を聞く
* 会員番号
* 名前
* 電話番号
* 生年月日

大抵の場合「xx 日に xx 番スタジオを xx 時から xx 時間」
といった感じで予約を受ける。
end note

rectangle 管理サイト {
    スタッフ --> (ログインする)
    スタッフ --> (予約する)
    (予約する) --> (予約を確定する)
    (予約する) --> (レンタル機材を選択する)
    (予約する) --> (利用者情報を入力する)
    (予約する) --> (利用会員を選択する)
    (予約する) --> (利用スタジオと利用時間枠を選択する)
    (予約する) --> (利用日付を選択する)

    note right of (ログインする)
    ログインID、パスワードでログインする。
    end note

    note right of (利用会員を選択する)
    利用者の会員番号、電話番号、名前、生年月日などの情報から検索する。
    非会員の場合は、選択不要。
    end note

    note right of (利用者情報を入力する)
    非会員の場合は、利用者名、電話番号を入力する。
    会員の場合は入力不要。
    end note

    スタッフ --> (予約をキャンセルする)
    (予約をキャンセルする) --> (キャンセルする)
    (予約をキャンセルする) --> (キャンセル対象の予約を選択する)

    note right of (予約をキャンセルする)
    キャンセル料がかかってしまう日付の場合は本管理サイトから予約をキャンセルする。
    end note

    スタッフ --> (レンタル機材を変更する)
    (レンタル機材を変更する) --> (変更する)
    (レンタル機材を変更する) --> (変更対象の予約を選択する)
}

@enduml
