@startuml Usecase

left to right direction

actor 利用者

rectangle Web予約 {
    利用者 --> (会員登録する)
    利用者 --> (ログインする)
    利用者 --> (利用日付を選択する)
    利用者 --> (利用スタジオと利用時間枠を選択する)
    利用者 --> (レンタル機材を選択する)
    利用者 --> (予約を確定する)
    利用者 --> (予約をキャンセルする)
    利用者 --> (支払う)

    note right of (利用スタジオと利用時間枠を選択する)
    スタジオごとに利用可能時間枠が表示される。
    end note

    note right of (レンタル機材を選択する)
    指定された利用日付の利用時間枠で空いている備品を選択できる。
    end note
    
    note right of (予約を確定する)
    利用日時、利用スタジオ、予約機材、を確認して確定する。
    この時料金も確認できる。利用料金は以下のように決まる。
    ■バンド練習
    * スタジオ、曜日区分（平日、土日祝）、時間帯で決まる。
    * 平日の 9:00 - 17:00 は、3時間パック、4時間パックが利用できる。

    ■個人練習
    * 人数、曜日区分（平日、土日祭）、時間帯（10-19、19-10）で決まる。

    料金設定はフレキシブルに変えられる必要がある。
    予約情報から料金を計算するようなモジュールが必要。
    end note

    note right of (予約をキャンセルする)
    キャンセル料は以下の通り。
    7日前まで無料
    2日前まで半額
    前日または当日はスタジオ利用料を全額（機材料金は除く）
    end note
}

@enduml
