@startuml Usecase

left to right direction

actor 利用者

rectangle 会員サイト {
    利用者 --> (ログインする)
    利用者 --> (予約する)
    利用者 --> (予約を変更する)
    利用者 --> (予約をキャンセルする)

    note right of (予約する)
    スタジオ、利用日時、レンタル機材
    などの情報を入力して予約する。
    end note
}

@enduml
