@startuml ContextMap

(予約コンテキスト) "D" -- "U" (管理コンテキスト)
(予約コンテキスト) "D" --> "U" (認証コンテキスト)
(管理コンテキスト) "D" --> "U" (認証コンテキスト)

note top of (予約コンテキスト)
スタジオの予約を行う。
end note

note left of (管理コンテキスト)
スタジオ情報、機材情報の管理を行う。
end note

note left of (認証コンテキスト)
ユーザー登録を行う。
ロール定義、各種操作可否の管理を行う。
end note

@enduml