@startuml DomainModel

package スタジオ
{
    class スタジオ
    {
        スタジオID
        スタジオ名
    }
}

package 機材
{
    class 機材
    {
        機材ID
        モデル名
    }

    class 機材在庫
    {
        在庫数
    }

    enum 機材種別
    {
        ドラム
        ギターアンプ
        ベースアンプ
        マイク
        シールド
    }

    機材 o-- "1" 機材種別
    機材 "1" o-- "1" 機材在庫
}

package ユーザーアカウント
{
    class ユーザーアカウント
    {
        ユーザーID
        メールアドレス
        パスワード
        ユーザー名
    }
}

package 予約
{
    class 予約
    {
        予約ID
        スタジオID
    }

    class 予約機材
    {
        機材ID
        数量
    }

    class 予約時間
    {
        開始時間
        終了時間
    }

    enum 練習区分
    {
        バンド練習
        個人練習
    }

    予約 "1" o-- "1" 練習区分
    予約 "1" o-- "1" 予約時間

    予約 "1" --> "1" スタジオ
    予約 "1" --> "0..*" 予約機材
    予約 "1" --> "1" ユーザーアカウント

    予約機材 --> "1" 機材

    note top of 予約
    同一時間帯に同一のスタジオを予約することはできない。
    同一時間帯に機材の在庫数が残っていなければ予約できない。
    end note

    note bottom of 予約時間
    1 時間単位での予約のみ可能
    end note

    note bottom of 練習区分
    個人練習は前日の 21:00 から予約可能
    end note
}

@enduml
