@startuml DomainModel

package 予約 {
    object 予約 {
        予約ID
        予約日時
        利用人数
    }

    object 利用者情報 {
        利用者名
        利用者電話番号
    }
}

package 練習区分 {
    object 練習区分 {
        バンド練習
        個人練習
    }

    object 最大利用人数 {
        人
    }

    object 予約受付開始日時 {
        開始日
        開始時間
    }

    object 開始日区分 {
        日前
        週間前
        ヶ月前
    }
}

package スタジオ {
    object スタジオ {
        スタジオID
        スタジオ名
    }

    object スタート時間区分 {
        0分スタート
        30分スタート
    }

    object 機材最大利用数 {
        最大利用数
    }
}

package 機材 {
    object 機材 {
        機材ID
        機材名
        在庫数
    }
}

package 機材カテゴリ {
    object 機材カテゴリ {
        機材カテゴリID
        機材カテゴリ名
    }
}

package キャンセル料金設定 {
    object キャンセル料金設定 {
    }

    object キャンセル料金レート {
        日前
        レート（パーセンテージ）
    }
}

package 営業時間 {
    object 営業時間 {
        営業開始時間
        営業終了時間
    }
}

package 会員アカウント {
    object 会員アカウント {
        会員ID
        メールアドレス
        パスワード
        会員名
        生年月日
        電話番号
    }
}

package スタッフアカウント {
    object スタッフアカウント {
        スタッフID
        ログインID
        パスワード
        スタッフ名
    }
}

package 利用料金設定 {
    object 利用料金設定 {
    }

    object 基本利用料金 {
        料金（/時間）
    }

    object 曜日区分 {
        平日
        土日
        祝日
    }

    object 時間帯 {
        開始時間
        終了時間
    }
}

package 料金計算 {
    object 料金計算 {
    }
}

package 請求 {
    object 請求 {
        請求金額
    }
}

予約 ----> "1" スタジオ
予約 ----> "0..*" 機材
予約 ----> "1" 練習区分
予約 o- "1" 利用者情報
利用者情報 -> "0..1" 会員アカウント

スタジオ o-- "1" スタート時間区分
スタジオ o-- "0..*" 機材最大利用数

機材最大利用数 --> "1" 機材カテゴリ

機材 ---> "1" 機材カテゴリ

練習区分 o-- "1" 最大利用人数
練習区分 o-- "1" 予約受付開始日時
予約受付開始日時 o-- "1" 開始日区分

キャンセル料金設定 o-- "0..*" キャンセル料金レート

利用料金設定 o-- "0..*" 基本利用料金
基本利用料金 ----> "1" 練習区分
基本利用料金 ----> "1" スタジオ
基本利用料金 o-left- "1" 曜日区分
基本利用料金 o-right- "1" 時間帯

請求 ---> "1" 予約
料金計算 ---> 予約
料金計算 ---> 利用料金設定
料金計算 -left-> 請求
料金計算 ---> キャンセル料金設定

@enduml
