@startuml DomainModel

package アカウント {
    class アカウント {
        アカウントID
        名前
        パスワード
    }

    アカウント --> "1..*" ロール

    note top of アカウント
    同じメールアドレスのアカウントを複数登録することはできない。
    end note
}

package ロール {
    class ロール {
        ロールID
        ロール名
    }

    class 権限 {
        権限ID
        権限名
    }

    enum 操作種別 {
        予約
        精算
        機材登録/変更
        スタジオ登録/変更
        料金設定
    }

    ロール o-- "1..*" 権限
    権限 o- "1..*" 操作種別

    note top of ロール
    現時点では以下の権限がある。
    アルバイト … 予約、精算
    社員 … 予約、精算、機材登録/変更
    管理者 … 予約、精算、機材登録/変更、スタジオ登録/変更、料金設定
    end note
}

@enduml
