@startuml DomainModel

package アカウント {
    class アカウント {
        アカウントID
        ログインID
        パスワード
        名前
    }

    アカウント --> "*" ロール

    note top of アカウント
    * 同じログインIDのアカウントを複数登録することはできない。
    * ログインIDは16文字以内の半角英数記号のみ許容する
    * パスワードは8文字以上16文字以内で、半角英数が1文字以上含まれている必要がある。
    end note
}

package ロール {
    class ロール {
        ロールID
        ロール名
    }

    class 権限 {
        権限ID
        権限名
    }

    enum 操作種別 {
        予約
        精算
        機材登録/変更
        スタジオ登録/変更
        料金設定
    }

    ロール o-- "1..*" 権限
    権限 o- "1..*" 操作種別

    note top of ロール
    現時点では以下の権限がある。
    アルバイト … 予約、精算
    社員 … 予約、精算、機材登録/変更
    管理者 … 予約、精算、機材登録/変更、スタジオ登録/変更、料金設定
    end note
}

@enduml
