@startuml DomainModel

package スタジオ {
    class スタジオ {
        スタジオID
    }
}

package 機材 {
    class 機材 {
        機材ID
    }

    class 在庫 {
    }

    機材 o-- "1" 在庫
}

package 会員 {
    class 会員 {
        会員ID
    }
}

package 予約 {
    class 予約 {
        予約ID
    }

    enum 練習区分 {
        バンド練習
        個人練習
    }

    class 利用機材 {
        機材ID
        数量
    }

    class 利用時間 {
        開始時間
        終了時間
    }

    class 利用人数 {
        人数
    }

    class 利用者情報 {
        利用者名
        電話番号
    }

    予約 "1" --> "1" スタジオ
    予約 "1" --> "1" 会員
    予約 "1" o-- "1" 練習区分
    予約 "1" o-- "1" 利用時間
    予約 "1" o-- "1" 利用人数
    予約 "1" o-- "0..1" 利用者情報
    予約 "1" --> "0..*" 利用機材
    利用機材 --> "1" 機材

    note right of 予約
    * 同一時間帯に同一のスタジオを予約することはできない。
    * 同一時間帯に機材の在庫数が残っていなければ予約できない。
    end note

    note bottom of 利用者情報
    電話予約、店頭予約で、会員登録していない利用者が予約した場合のみ
    利用者情報が必須で必要。
    end note

    class 予約機材 {
    }

    class 予約機材数量 {
    }

    予約機材 o-- "*" 利用機材
    予約機材 --> 予約機材数量

    note left of 予約機材
    複数の予約に紐づく利用機材を束ね、
    各機材の予約数量を計算する。
    例えば、
    ある時間帯の複数の予約で利用されていル機材を束ね、
    機材の在庫数以上予約されていないかをチェックチェックするとき
    などに利用する。
    end note


    rectangle 予約仕様 {
        
        class 予約開始日時仕様 {
        }

        class 予約開始日時 {
            開始日
            開始時間
        }

        class 予約開始日区分 {
            日前
            週間前
            カ月前
        }

        予約開始日時仕様 --> 予約
        予約開始日時 "2" --o 予約開始日時仕様
        予約開始日時 o- 予約開始日区分

        note top of 予約開始日時
        練習区分ごとに予約開始日時を持つ
        * 個人練習は前日の 21 時から予約可。
        * バンド練習は 2 カ月前から予約可。
        end note


        class 最大利用人数仕様 {
        }

        class 最大利用人数 {
        }

        最大利用人数仕様 --> 予約
        最大利用人数 "1" --o 最大利用人数仕様

        note top of 最大利用人数
        練習区分ごとに設定を持つ
        （基本的に個人練習のみ上限を持つ）
        * 個人練習は 2 人まで利用可。
        end note


        class スタート時間仕様 {
        }

        enum スタート時間区分 {
            0分スタート
            30分スタート
        }

        スタート時間仕様 --> 予約
        スタート時間区分 "*" --o スタート時間仕様

        note top of スタート時間区分
        スタジオごとに持つ
        例）
        * スタジオAは 0 分スタート
        * スタジオBは 30 分スタート
        end note    
    }
}

@enduml
