@startuml DomainModel

package アカウント {
    class アカウント {
        アカウントID
        名前
        生年月日
        住所
    }

    class アカウント認証情報 {
        メールアドレス
        パスワード
    }

    アカウント "1" o-- "1" アカウント認証情報
    アカウント --> 権限

    note top of アカウント
    同じメールアドレスのアカウントを複数登録することはできない。
    end note
}

package 権限 {
    class 権限 {
        権限ID
        権限名
        操作可能(操作種別)
    }

    class 認可 {
        操作可能
    }

    enum 操作種別 {
        予約
        スタジオ管理
        機材管理
        精算
    }

    権限 o-- "0..*" 認可
    認可 o- "1" 操作種別
    権限 --> 操作種別

    note top of 権限
    現時点では以下の権限がある。
    管理者・・・予約、スタジオ管理、機材管理、精算
    スタッフ・・・予約、精算
    利用者・・・予約
    end note
}

@enduml
