@startuml DomainModel

package 店舗設定 {
    class 店舗設定
    
    class 店舗名

    class 営業時間 {
        開始時間
        終了時間
    }

    enum 練習区分 {
        バンド練習
        個人練習
    }
    
    class 利用上限人数

    class 予約受付開始日時 {
        開始日
        開始日区分
        開始時間
    }
    enum 予約受付開始日区分 {
        日前
        週間前
        ヶ月前
    }
    予約受付開始日時 o-- "1" 予約受付開始日区分

    class キャンセル料金レート {
        日前から
        レート
    }

    店舗設定 o-- "1" 店舗名
    店舗設定 o-- "1" 営業時間
    店舗設定 o-- "2" 予約受付開始日時 : バンド練習、個人練習
    店舗設定 o-- "1" 利用上限人数 : 個人練習
    店舗設定 o-- "*" キャンセル料金レート
    店舗設定 -> 練習区分
}

package スタジオ {
    class スタジオ {
        スタジオID
    }

    class スタジオ名
    class 広さ

    enum スタート時間区分 {
        0分スタート
        30分スタート
    }

    スタジオ o-- "1" スタジオ名
    スタジオ o-- "1" 広さ
    スタジオ o-- "1" スタート時間区分
}

package 機材カテゴリ {
    class 機材カテゴリ {
        機材種別ID
    }
    class 機材カテゴリ名
    機材カテゴリ o-- "1" 機材カテゴリ名

    note top of 機材カテゴリ
    アンプ、キーボード、マイクなどのカテゴリ
    end note
}

package 機材 {
    class 機材 {
        機材ID
    }
    class 機材名
    class 機材在庫数
    
    機材 --> "1" 機材カテゴリ
    機材 o-- "1" 機材名
    機材 o-- "1" 機材在庫数

    note top of 機材
    アンプ、キーボード、特殊なマイクなど少数しか入荷できないものを管理対象とする。
    シールドなど大量入荷可能である機材などは予約するまでもなく利用できるため管理する想定ではないが、
    当日スムーズにいくように管理させても良い。
    end note
}

@enduml
