@startuml DomainModel

package 予約 {
    object 予約 {
        予約ID
        利用日時
        利用人数
    }

    object 予約状態 {
        予約済
        キャンセル
    }

    object 利用者情報 {
        利用者名
        利用者電話番号
    }

    object 利用機材 {
        数量
    }
}

package 練習区分設定 {
    object 練習区分設定 {
    }

    object 練習区分 {
        バンド練習
        個人練習
    }

    object 最大利用人数 {
        人
    }

    object 予約受付開始日時 {
        開始日
        開始時間
    }

    object 開始日区分 {
        日前
        週間前
        ヶ月前
    }
}

package スタジオ {
    object スタジオ {
        スタジオID
        スタジオ名
    }

    object スタート時間区分 {
        0分スタート
        30分スタート
    }

    object 機材最大利用数 {
        最大利用数
    }
}

package 機材 {
    object 機材 {
        機材ID
        機材名
        在庫数
    }
}

package 機材カテゴリ {
    object 機材カテゴリ {
        機材カテゴリID
        機材カテゴリ名
    }
}

package 営業時間設定 {
    object 営業時間設定 {
    }

    object 営業時間 {
        営業開始時間
        営業終了時間
    }
}

package 会員アカウント {
    object 会員アカウント {
        会員ID
        メールアドレス
        パスワード
        会員名
        生年月日
        電話番号
    }
}

package スタッフアカウント {
    object スタッフアカウント {
        スタッフID
        ログインID
        パスワード
        スタッフ名
    }
}

package 利用料金設定 {
    package 基本料金設定 {
        object 基本料金設定 {
        }

        object 練習区分利用料金設定 {
        }

        object 基本料金 {
        }
    }

    package パック料金設定 {
        object パック料金設定 {
            パック料金設定ID
            パック名
        }

        object パック料金 {
        }
    }

    object 利用料金 {
    }

    object 時間利用料金 {
        料金/h
    }

    object 固定利用料金 {
        料金
    }
    
    object 料金条件 {
        スタジオ
        曜日区分
        利用人数
        時間帯
        利用時間（固定、時間以上）
    }
}

package キャンセル料金設定 {
    object キャンセル料金設定 {
    }

    object キャンセル料金レート {
        日前
        レート（パーセンテージ）
    }
}

package 請求 {
    object 請求 {
        請求金額
    }

    object 請求明細 {
        内容
        請求金額
    }
}

予約 o-- "0..*" 利用機材
予約 o-right- "1" 利用者情報
予約 o-- "1" 予約状態
予約 ----> "1" スタジオ
予約 ----> "1" 練習区分
予約 -up--> "0..1" 会員アカウント

利用機材 ---> "1" 機材

スタジオ o-- "1" スタート時間区分
スタジオ o-- "0..*" 機材最大利用数

機材最大利用数 --> "1" 機材カテゴリ

機材 ---> "1" 機材カテゴリ

練習区分設定 o- "1" 練習区分
練習区分設定 o-- "1" 最大利用人数
練習区分設定 o-- "1" 予約受付開始日時
予約受付開始日時 o-- "1" 開始日区分

営業時間設定 o-- "1" 営業時間

キャンセル料金設定 o-- "0..*" キャンセル料金レート

基本料金設定 o-- "2" 練習区分利用料金設定
練習区分利用料金設定 o-- "0..*" 基本料金
練習区分利用料金設定 --> "1" 練習区分
基本料金 o-- "1" 利用料金
基本料金 o---- "0..*" 料金条件

パック料金設定 o-- "0..*" パック料金
パック料金 o-- "1" 利用料金
パック料金 o---- "0..*" 料金条件

利用料金 <|-- 時間利用料金
利用料金 <|-- 固定利用料金

料金条件 ---> "0..1" スタジオ

請求 o-up- "1..*" 請求明細
請求 --> "1" 予約

@enduml
