@startuml BusinessFlow

|利用者|
start
:予約内容を伝える;

|スタッフ|
:予約されていることを確認する;
note right
予約日付の空き状況一覧を表示して、
予約を特定する。
end note

partition 必要に応じて {
    |利用者|
    :追加で機材をレンタルする;

    |スタッフ|
    :予約を変更する;
    note right
    電話予約/店頭予約の予約変更のフローで、
    レンタル機材の変更のみを行う。
    end note
}

|スタッフ|
:レンタル機材を渡す;

stop

@enduml
