@startuml BusinessFlow

|利用者|
partition 予約 {
    start
    :スタジオの空きを調べる;
    note left
    選択された日付の空き状況一覧を表示して、
    スタジオの予約が空いている時間帯を調べる。
    end note

    :予約する;
    note left
    スタジオ、時間帯、レンタル機材などの
    予約内容を入力して予約する。
    end note
    stop
}


|利用者|
partition 予約変更 {
    start
    :変更対象の予約を選ぶ;
    note left
    会員ページの予約一覧から変更対象の予約を選ぶ。
    end note

    :予約を変更する;
    note left
    予約変更内容を入力して予約変更する。
    end note
    stop
}


|利用者|
partition 予約キャンセル {
    start
    :キャンセル対象の予約を選ぶ;
    note left
    会員ページの予約一覧から変更対象の予約を選ぶ。
    end note

    :予約をキャンセルする;
    note left
    キャンセルする。
    end note
    stop
}

|スタッフ|

@enduml
