@startuml BusinessFlow

|利用者|
partition 予約 {
    start
    :予約したい旨を伝える;

    |スタッフ|
    :予約内容を聞く;

    |利用者|
    :予約内容を伝える;

    |スタッフ|
    :スタジオの空きを確認する;
    note right
    利用日付の空き状況一覧を表示して、
    予約が空いているかを調べる。
    end note
    
    :予約内容の登録を始める;
    note right
    予約画面を開いて予約内容を入力する。
    end note

    :レンタル機材があるか聞く;

    |利用者|
    :レンタル機材の内容を伝える;

    |スタッフ|
    :レンタル機材の空きを確認する;
    note right
    予約画面に表示されている
    機材の残り在庫数を確認する。
    end note

    :予約内容にレンタル機材を入力する;
    note right
    予約画面にレンタル機材の
    数量を入力する。
    end note

    :名前と連絡先を聞く;

    |利用者|
    :名前と連絡先を伝える;

    |スタッフ|
    :予約内容に名前と連絡先を入力する;
    note right
    予約画面に利用者情報として
    名前と連絡先を入力する。
    end note

    :予約内容を最終確認する;
    note right
    確認するボタンなどから予約確認画面に遷移し、
    予約内容、利用料金を確認する。
    予約内容に不備がある場合や予約が埋まっている場合はエラー表示する。
    end note

    :予約の意思を最終確認する;

    |利用者|
    :予約確定の旨を伝える;

    |スタッフ|
    :予約を確定する;
    note right
    予約確認画面で予約を確定する。
    予約内容に不備がある場合や予約が埋まっている場合はエラー表示する。
    end note

    stop
}


|利用者|
partition 予約変更 {
    start
    :予約を変更したい旨を伝える;

    |スタッフ|
    :予約内容を聞く;

    |利用者|
    :予約内容を伝える;

    |スタッフ|
    :予約されていることを確認する;
    note right
    予約日付の空き状況一覧を表示して、
    予約を特定する。
    end note

    :変更内容によっては
    キャンセル料金が発生する可能性があることを伝える;
    note right
    予約画面に表示された
    キャンセル料金に関する情報を確認して伝える。

    ＜メモ＞
    キャンセル料金が発生する日付になっていた場合は
    予約画面にキャンセル料金が発生する可能性があることを表示する。
    end note

    |利用者|
    :問題ないことを伝える;

    |スタッフ|
    :予約変更内容を聞く;

    |利用者|
    :予約変更内容を伝える;

    |スタッフ|
    :変更内容の登録を始める;
    note right
    予約画面に変更内容を入力する。
    end note

    :レンタル機材の変更があるか聞く;

    |利用者|
    :レンタル機材の変更内容を伝える;

    |スタッフ|
    :レンタル機材の空きを確認する;
    note right
    予約画面に表示されている
    機材の残り在庫数を確認する。
    end note

    :予約内容にレンタル機材を入力する;
    note right
    予約画面にレンタル機材の
    数量を入力する。
    end note

    :予約内容を最終確認する;
    note right
    確認するボタンなどから予約確認画面に遷移し、
    予約内容、利用料金を確認する。
    キャンセル料金についても表示される。
    予約内容に不備がある場合や予約が埋まっている場合はエラー表示する。
    end note

    :予約の意思を最終確認する;

    |利用者|
    :予約確定の旨を伝える;

    |スタッフ|
    :予約を確定する;
    note right
    予約確認画面で予約を確定する。
    予約内容に不備がある場合や予約が埋まっている場合はエラー表示する。
    end note

    stop
}

|利用者|
partition 予約キャンセル {
    start
    :予約をキャンセルしたい旨を伝える;

    |スタッフ|
    :予約内容を聞く;

    |利用者|
    :予約内容を伝える;

    |スタッフ|
    :予約されていることを確認する;
    note right
    予約日付の空き状況一覧を表示して、
    予約を特定する。
    end note

    :キャンセル内容を確認する;
    note right
    予約画面からキャンセルを行い、キャンセル確認画面に遷移し、
    キャンセル料金を確認する。
    end note

    :キャンセルの意思を最終確認する;

    |利用者|
    :キャンセル確定の旨を伝える;

    |スタッフ|
    :キャンセルを確定する;

    note right
    非会員によるキャンセルの場合、キャンセル料金を支払いに来るよう伝える。
    会員によるキャンセルの場合、自動的に次回の予約に上乗せされる。
    end note
    
    stop
}

@enduml
