@startuml BusinessUsecase

left to right direction

actor 利用者
actor スタッフ

rectangle 予約 {
    利用者 -- (Web予約)
    利用者 -- (電話/店頭予約)
    (Web予約)  -- スタッフ

    note top of (Web予約)
    * 利用者は、Web でスタジオと機材の予約ができなければならない。
    * 利用者は、予約内容の変更、予約のキャンセルもできなければならない。
    * 利用者は、予約の際にスタジオと機材の空き状況を確認できなければならない。
    end note

    note top of (電話/店頭予約)
    * 利用者は、電話や店頭で予約できなければならない。
    * スタッフは、電話や店頭での予約に対応するため、利用者の予約を登録できなければならない。
    * スタッフは、予約内容の変更、予約のキャンセルもできなければならない。
    * スタッフは、電話や店頭での予約に対応するため、スタジオと機材の空き状況を確認できなければならない。
    end note
}

rectangle スタジオ利用 {
    (スタジオ準備) -- スタッフ
    利用者 -- (受付)
    (受付) -- スタッフ

    利用者 -- (スタジオ利用)
    (スタジオ利用) -- スタッフ

    note top of (スタジオ準備)
    * スタッフは、スタジオの転換を行うため、予約内容を確認できなければならない。
    end note

    note top of (受付)
    * 利用者は、受付の際や、スタジオでの練習中に機材をレンタルできなければならない。
    end note

    note top of (スタジオ利用)
    * 利用者は、受付の際や、スタジオでの練習中に機材をレンタルできなければならない。
    end note
}

rectangle 会計 {
    利用者 -- (会計)
    (会計) -- スタッフ

    note top of (会計)
    * スタッフは、予約に対する利用料金を確認できなければならない。
    * スタッフは、予約のキャンセル料金を確認できなければならない。
    end note
}

rectangle 会員管理 {
    (会員アカウント管理) -- スタッフ
    利用者 -- (会員アカウント登録)
    
    note top of (会員アカウント管理)
    * スタッフは、会員アカウントを確認/変更/削除できなければならない。
    end note

    note top of (会員アカウント登録)
    * 利用者は、システムを利用するために会員アカウントを登録できなければならない。
        システムにログインするためには、メールアドレスとパスワードが一致しなければならない。
    end note
}

rectangle スタッフ管理 {
    (スタッフアカウント管理) -- スタッフ

    note top of (スタッフアカウント管理)
    * スタッフは、システムを利用するためにスタッフアカウントを登録できなければならない。
        システムにログインするためには、ユーザー ID とパスワードが一致しなければならない。
    end note
}

rectangle 設備管理 {
    (スタジオ管理) -- スタッフ
    (機材管理) -- スタッフ
    (利用料金管理) -- スタッフ
    (店舗管理) -- スタッフ

    note top of (スタジオ管理)
    * スタッフは、スタジオの情報をシステムに登録できなければならない。
    end note

    note top of (機材管理)
    * スタッフは、機材の情報をシステムに登録できなければならない。
    * スタッフは、機材の在庫数をシステムに登録できなければならない。
    end note

    note top of (利用料金管理)
    * スタッフは、スタジオの利用料金を設定できなければならない。
    * スタッフは、機材のレンタル料金を設定できなければならない。
    * スタッフは、キャンセル料金を設定できなければならない。
    end note

    note top of (店舗管理)
    * スタッフは、店舗の情報をシステムに登録できなければならない。
    end note
}

@enduml
