@startuml BusinessFlow

|利用者|
partition 予約 {
    start
    :予約したい旨を伝える;

    |スタッフ|
    :予約内容を聞く;

    |利用者|
    :予約内容を伝える;

    |スタッフ|
    :スタジオの空きを確認する;
    :レンタル機材があるか聞く;

    |利用者|
    :レンタル機材の内容を伝える;

    |スタッフ|
    :レンタル機材の空きを確認する;
    :名前と連絡先を聞く;

    |利用者|
    :名前と連絡先を伝える;

    |スタッフ|
    :予約台帳に予約内容を記載する;

    stop
}

|利用者|
partition 予約変更 {
    start
    :予約を変更したい旨を伝える;

    |スタッフ|
    :予約内容を聞く;

    |利用者|
    :予約内容を伝える;

    |スタッフ|
    :予約されていることを確認する;
    :予約変更内容を聞く;

    |利用者|
    :予約変更内容を伝える;

    |スタッフ|
    :キャンセル料金が発生するか確認する;

    if (キャンセル料金が発生する) then (yes)
        :キャンセル料金を計算する;
        :キャンセル料金を伝え、予約変更の意思を聞く;
        
        |利用者|
        :問題ないことを伝える;
    endif

    |スタッフ|
    :スタジオの空きを確認する;

    :レンタル機材の変更があるか聞く;

    |利用者|
    :レンタル機材の変更内容を伝える;

    |スタッフ|
    :レンタル機材の空きを確認する;
    :予約台帳の予約内容を変更する;
    
    if (キャンセル料金が発生する) then (yes)
        :予約キャンセル台帳にキャンセル料金を記載する;
    endif

    stop
}

|利用者|
partition 予約キャンセル {
    start
    :予約をキャンセルしたい旨を伝える;

    |スタッフ|
    :予約内容を聞く;

    |利用者|
    :予約内容を伝える;

    |スタッフ|
    :予約されていることを確認する;
    :キャンセル料金が発生するか確認する;

    if (キャンセル料金が発生する) then (yes)
        :キャンセル料金を計算する;
        :キャンセル料金を伝え、予約キャンセルの意思を聞く;
        
        |利用者|
        :問題ないことを伝える;
    endif

    |スタッフ|
    :予約台帳から予約内容を消す;
    
    if (キャンセル料金が発生する) then (yes)
        :予約キャンセル台帳にキャンセル料金を記載する;
    endif

    stop
}

@enduml
