@startuml BusinessFlow

|利用者|
partition 予約 {
    start
    :新規予約の内容を伝える;

    |スタッフ|
    :空きがあるかを調べる;
    note right
    UC:
    * スタジオの空きを調べる
    * 機材の空きを調べる
    end note

    :会員かどうかを調べる;
    note right
    UC:
    会員アカウントを検索する
    end note
    :予約する;
    note right
    UC:
    予約する
    
    ＜Note＞
    * 会員アカウントが見つからなかった場合は非会員として予約する。
    end note
    stop
}


|利用者|
partition 予約変更 {
    start
    :予約の変更内容を伝える;

    |スタッフ|
    :予約を変更する;
    note right
    UC:
    * 予約を特定する
    * 予約を変更する
    end note
    stop
}


|利用者|
partition 予約キャンセル {
    start
    :予約のキャンセルを伝える;

    |スタッフ|
    :予約をキャンセルする;
    note right
    UC:
    * 予約を特定する
    * 予約をキャンセルする
    end note
    :キャンセル料金を伝える;
    note right
    UC:
    キャンセル料金を確認する
    end note

    |利用者|
    stop
}

@enduml
