@startuml BusinessFlow

|利用者|

|スタッフ|
start
:会員を検索する;
note right
UC:
会員アカウントを検索する
end note

:会員情報を確認する;
note right
UC:
会員アカウントの内容を確認する
end note

fork
:会員情報を変更する;
note right
UC:
会員アカウントを変更する
end note
stop

fork again
:会員を強制退会させる;
note right
UC:
会員アカウントを削除する
end note
stop

@enduml
