@startuml BusinessContext

left to right direction

actor 利用者
actor スタッフ

利用者 -- (予約)
(予約) -- スタッフ

利用者 -- (スタジオ利用)
(スタジオ利用) -- スタッフ

利用者 -- (会計)
(会計) -- スタッフ

利用者 -- (会員管理)
(会員管理) -- スタッフ

(スタッフ管理) -- スタッフ
(設備管理) -- スタッフ

note top of (予約)
* 利用者は、Web でスタジオと機材の予約ができなければならない。
* 利用者は、予約内容の変更、予約のキャンセルもできなければならない。
* 利用者は、予約の際にスタジオと機材の空き状況を確認できなければならない。
* 利用者は、電話や店頭で予約できなければならない。
* スタッフは、電話や店頭での予約に対応するため、利用者の予約を登録できなければならない。
* スタッフは、予約内容の変更、予約のキャンセルもできなければならない。
* スタッフは、電話や店頭での予約に対応するため、スタジオと機材の空き状況を確認できなければならない。
end note

note top of (スタジオ利用)
* スタッフは、スタジオの転換を行うため、予約内容を確認できなければならない。
* 利用者は、受付の際や、スタジオでの練習中に機材をレンタルできなければならない。
end note

note top of (会計)
* スタッフは、予約に対する利用料金を確認できなければならない。
* スタッフは、予約のキャンセル料金を確認できなければならない。
end note

note top of (会員管理)
* 利用者は、システムを利用するために会員アカウントを登録できなければならない。
    システムにログインするためには、メールアドレスとパスワードが一致しなければならない。
* スタッフは、会員アカウントを確認/変更/削除できなければならない。
end note

note top of (スタッフ管理)
* スタッフは、システムを利用するためにスタッフアカウントを登録できなければならない。
    システムにログインするためには、ユーザー ID とパスワードが一致しなければならない。
end note

note top of (設備管理)
* スタッフは、スタジオの情報をシステムに登録できなければならない。
* スタッフは、機材の情報をシステムに登録できなければならない。
* スタッフは、機材の在庫数をシステムに登録できなければならない。
* スタッフは、機材のレンタル料金を設定できなければならない。
* スタッフは、スタジオの利用料金を設定できなければならない。
* スタッフは、キャンセル料金を設定できなければならない。
* スタッフは、店舗の情報をシステムに登録できなければならない。
end note

@enduml
