@startuml BusinessFlow

|利用者|
start
:スタジオで練習する;

partition 必要に応じて {
    :追加で機材をレンタルする;

    |スタッフ|
    :機材のレンタル料金を伝え、レンタルするかを確認する;
    note right
    UC:
    * 予約を特定する
    * レンタル機材の内容を入力する
    * レンタル機材の内容を確認する
    end note

    |利用者|
    :機材のレンタルの意思を伝える;

    |スタッフ|
    :機材のレンタルを確定する;
    note right
    UC:
    機材のレンタルを確定する
    end note
}

:終了 5 分前のランプを点灯する;

|利用者|
:退出する;

stop

@enduml
