@startuml BusinessFlow

|利用者|
start
:予約内容を伝える;

|スタッフ|
:予約されていることを確認する;

partition 必要に応じて {
    |利用者|
    :追加で機材をレンタルする;

    |スタッフ|
    :レンタル機材の空きを確認する;
    :予約台帳の予約内容を変更する;
}

|スタッフ|
:レンタル機材を渡す;

stop

@enduml
