@startuml BusinessContext

left to right direction

actor 利用者
actor スタッフ

利用者 -- (会員管理)
(会員管理) -- スタッフ

利用者 -- (予約)
(予約) -- スタッフ

利用者 -- (スタジオ利用)
(スタジオ利用) -- スタッフ

利用者 -- (会計)
(会計) -- スタッフ

(設備管理) -- スタッフ

@enduml
