@startuml BusinessFlow

|利用者|
start
:レンタル機材を返却する;

|スタッフ|
:レンタル機材が全て返却されているかどうかを確認する;
note right
予約内容を確認し、照らし合わせる。
end note

:利用料金を確認する;
note right
予約の利用料金を確認する。
end note

:料金を伝える;

|利用者|
:支払いする;

|スタッフ|
:支払い済みにする;
note right
予約を支払済にする。
end note

stop

@enduml
