@startuml BusinessFlow

|利用者|
start
:レンタル機材を返却する;

|スタッフ|
:レンタル機材が全て返却されたかどうかを確認する;
:キャンセル料金を確認する;
:利用料金を計算する;
:利用料金を伝える;

|利用者|
:支払いする;

|スタッフ|
:予約台帳に支払い済みであることを記載する;
:予約キャンセル台帳に支払い済みであることを記載する;

stop

@enduml
