@startuml BusinessFlow

|利用者|
start
:スタジオで練習する;

partition 必要に応じて {
    :追加で機材をレンタルする;

    |スタッフ|
    :レンタル機材の空きを確認する;
    :レンタル機材を渡す;
    :予約台帳の予約内容を変更する;
}

:終了 5 分前にランプを点灯する;

|利用者|
:片付ける;
:退出する;

stop

@enduml
