@startuml BusinessFlow

|利用者|
start
:スタジオで練習する;

partition 必要に応じて {
    |利用者|
    :追加で機材をレンタルする;

    |スタッフ|
    :予約を変更する;
    note right
    電話予約/店頭予約の予約変更のフローで、
    レンタル機材の変更のみを行う。
    end note
}

:終了 5 分前のランプを点灯する;

|利用者|
:片付ける;

:退出する;

stop

@enduml
