@startuml BusinessFlow

|利用者|
partition 会員登録 {
    start
    :会員登録する;
    note left
    UC:
    会員アカウントを登録する
    end note
    stop
}


|利用者|
partition 会員変更 {
    start
    :会員情報を確認する;
    note left
    UC:
    会員アカウントを確認する
    end note
    :会員情報を変更する;
    note left
    UC:
    会員アカウントを変更する
    end note
    stop
}


|利用者|
partition 退会 {
    start
    :退会する;
    note left
    UC:
    会員アカウントを削除する
    end note
    stop
}

|スタッフ|

@enduml
