@startuml DomainModel

package 予約 {
    object 予約
    object 予約内容 {
        利用人数
    }

    object 利用日時 {
        開始日時
        終了日時
    }

    object レンタル機材 {
        数量
    }

    object 利用料金

    object 基本料金 {
        利用時間
        料金
        料金区分（時間毎、固定）
    }

    object パック料金 {
        パック名
        利用時間
        料金
        料金区分（時間毎、固定）
    }

    object レンタル機材料金 {
        利用時間
        料金
        料金区分（時間毎、固定）
        数量
    }
}

package 予約ポリシー {
    object 予約ポリシー {
        営業時間
        スタート時間
        予約受付開始日
        最大利用人数
        最大レンタル機材数量
    }

    object 予約変更ポリシー
}

package 利用者 {
    object 利用者
    object 会員

    object 非会員 {
        名前
        電話番号
    }
}

package 練習区分 {
    object 練習区分 {
        バンド練習
        個人練習
    }
}

package スタジオ {
    object スタジオ
}

package 機材 {
    object 機材 {
        在庫
        レンタル料金
    }
}

package 利用料金設定 {
    object 利用料金設定
    object 基本料金設定
    object パック料金設定 {
        パック名
    }

    object 利用料金仕様 {
        練習区分仕様
        スタジオ仕様
        曜日区分仕様
        利用人数仕様（何人から何人まで）
        時間帯仕様（開始時間、終了時間）
        利用時間仕様（分以上、分固定）
        料金
        料金区分（時間毎、固定）
    }
}

package キャンセル料金設定 {
    object キャンセル料金設定
    object キャンセル料金レート {
        日前
        レート（%）
    }
}

予約 o-- "1" 予約内容
予約 o-- "1" 利用料金

予約内容 ---> "1" 利用者
予約内容 ---> "1" スタジオ
予約内容 ---> "1" 練習区分
予約内容 o-- "1" 利用日時
予約内容 o-- "*" レンタル機材

レンタル機材 --> "1" 機材

利用者 <|-- 会員
利用者 <|-- 非会員

利用料金 o-- "*" 基本料金
利用料金 o-- "*" パック料金
利用料金 o-- "*" レンタル機材料金

レンタル機材料金 --> "1" 機材

利用料金設定 o-- "1" 基本料金設定
利用料金設定 o-- "*" パック料金設定
基本料金設定 o-- "*" 利用料金仕様
パック料金設定 o-- "*" 利用料金仕様

利用料金仕様 -----> "0..1" スタジオ
利用料金仕様 -----> "0..1" 練習区分

予約ポリシー --> "*" 機材
予約変更ポリシー --> "1" 利用料金設定
予約変更ポリシー --> "1" キャンセル料金設定

予約ポリシー ......> 予約内容 : 検証
予約変更ポリシー ......> 予約内容 : 検証

キャンセル料金設定 o-- "*" キャンセル料金レート

@enduml
