@startuml LayerStructure

skinparam sequence {
    ArrowColor #Black
}
skinparam NoteBorderColor #Black
skinparam NodeFontStyle Bold

rectangle {
    node "プレゼンテーション（Presentation）" as Presentation #dae8fc
    node "ユースケース（UseCase）" as UseCase #d5e8d4
    node "ドメイン（Domain）" as Domain #ffe6cc
    node "インフラストラクチャ（Infrastructure）" as Infrastructure #f8cecc

    Presentation --> UseCase
    Presentation --> Domain
    UseCase --> Domain
    Infrastructure -up-> Domain
    Infrastructure -up-> UseCase
    Infrastructure -up-> Presentation
}

note right of Presentation
画面の入出力、API のエンドポイントとなる。
end note

note right of UseCase
Domain 層のオブジェクトを利用してユースケースを実現する。
end note

note right of Domain
ビジネスルールを表現する。
end note

note right of Infrastructure
上位レイヤーを実現するための技術的機能を提供する。
end note

@enduml
