@startuml LayerStructure

package domain
{
    package model {
        interface Repository
        class DomainService
        class DomainObject
        {
            Entity
            ValueObject
        }
    }
}

package usecase
{
    package command {
        class CommandService
    }

    package query {
        interface QueryService
    }
}

package infrastructure
{
    class RepositoryImpl
    class QueryServiceImpl
}

package api
{
    class Controller
}

DomainService -> Repository
DomainService -> DomainObject
Repository --> DomainObject

CommandService --> Repository
CommandService --> DomainObject
CommandService --> DomainService

Repository <|--- RepositoryImpl
QueryService <|--- QueryServiceImpl

Controller --> CommandService
Controller --> QueryService

@enduml
