@startuml LayerStructure_TypicalClass

skinparam sequence {
    ArrowColor #Black
}
skinparam NoteBorderColor #Black

rectangle {
    package "プレゼンテーション（Presentation）" as Presentation #dae8fc {
        class Controller
    }

    package "ユースケース（UseCase）" as UseCase #d5e8d4 {
        class CommandService
        interface QueryService
    }

    package "ドメイン（Domain）" as Domain #ffe6cc {
        class DomainObject {
            ValueObject
            Entity
            Aggregate
            DomainService
        }
        interface Repository
        interface Service
    }

    package "インフラストラクチャ（Infrastructure）" as Infrastructure #f8cecc {
        class RepositoryImpl
        class ServiceImpl
        class QueryServiceImpl
    }

    Controller --> CommandService
    Controller --> QueryService
    Controller --> DomainObject

    CommandService --> DomainObject
    CommandService --> Repository
    CommandService --> DomainObject

    RepositoryImpl .up.|> Repository
    ServiceImpl .up.|> Service
    QueryServiceImpl .up.|> QueryService

    Repository -> DomainObject
    Service -> DomainObject

    RepositoryImpl -up-> DomainObject
    ServiceImpl -up-> DomainObject
    QueryServiceImpl -up-> DomainObject
}

@enduml
