@startuml LayerStructure

package domain
{
    package model {
        interface IRepository
        class DomainService
        class DomainObject
        {
            Entity
            ValueObject
        }
    }

    package exception {
        class DomainException
    }
}

package application
{
    package command {
        class AppService
    }

    package query {
        interface IQuery
    }
}


package infrastructure
{
    class Repository
    class Query
}

package api
{
    class Controller
}

DomainService -> IRepository
DomainService --> DomainObject
IRepository --> DomainObject

AppService --> IRepository
AppService --> DomainObject
AppService --> DomainService
AppService --> DomainException

IRepository <|---- Repository
IQuery <|---- Query
Repository --> DomainObject

Controller --> AppService
Controller --> IQuery
Controller --> DomainException

@enduml
