@startuml RequirementModel

left to right direction

actor 利用者
note right : スタジオ、機材の空き情報を確認したい。（予約するため。）
actor 利用者
note right : スタジオ、機材の利用料金を確認したい。（予約するため。）
actor 利用者
note right : スタジオ、機材を Web で予約したい。（電話が手間であるため。）

actor スタッフ
note right : 予約当日の電話受付をしたくない。（スタジオの転換作業で忙しいため。）
actor スタッフ
note right : 予約内容を確認したい。（空いた時間で準備をしたいため。）
actor スタッフ
note right : スタジオ、機材の空き状況を把握したい。（電話予約、当日予約に対応するため。）
actor スタッフ
note right : スタジオ、機材の利用料金を計算したくない。（めんどくさいし、間違いも起きやすいため。）

@enduml
