@startuml SiteStructure

left to right direction

actor 利用者
actor スタッフ
actor 管理者

rectangle 会員サイト
rectangle 管理サイト

利用者 --> 会員サイト
スタッフ --> 管理サイト
管理者 --> 管理サイト
管理者 --> 会員サイト

note right of 会員サイト
会員がスタジオを予約するためのサイト。
end note

note right of 管理サイト
スタッフが業務で使用するサイト。
end note

@enduml
