@startuml SiteStructure

left to right direction

actor 利用者
actor スタッフ
actor 管理スタッフ

rectangle 会員サイト
rectangle 管理サイト

利用者 --> 会員サイト
スタッフ --> 管理サイト
管理スタッフ --> 管理サイト
管理スタッフ --> 会員サイト

note right of 会員サイト
* 会員登録
* スタジオ予約
end note

note right of 管理サイト
* スタッフ管理
* スタジオ管理
* 機材管理
* 予約管理（スケジュール確認、予約）
end note

@enduml
