@startuml SiteStructure

left to right direction

actor 会員
actor スタッフ
actor 管理スタッフ

rectangle 会員サイト
rectangle 管理サイト

会員 --> 会員サイト
スタッフ --> 管理サイト
管理スタッフ --> 管理サイト
管理スタッフ --> 会員サイト

note right of 会員サイト
* 会員登録
* スタジオ予約
end note

note right of 管理サイト
* 予約スケジュール確認
* スタジオ予約（電話、店頭での予約）
* 各種マスタ管理
end note

@enduml
