@startuml SystemContext

left to right direction

actor 利用者
actor スタッフ

usecase (スタジオ予約システム) as studioReservationSystem

利用者 -- studioReservationSystem
スタッフ -- studioReservationSystem

note top of studioReservationSystem
<b>システム化の目的</b>
予約の業務を効率化することで、スタッフの作業負担を減らし、人件費を削減する。
end note

@enduml
