@startuml SystemContext

left to right direction

actor 利用者
actor スタッフ

usecase (スタジオ予約システム) as studioReservationSystem

利用者 -- studioReservationSystem
スタッフ -- studioReservationSystem

note top of studioReservationSystem
<b>システム化の目的</b>
利用者が Web でスタジオ予約できるようにすることで、
スタッフの作業を効率化する。
end note

@enduml
