@startuml UsageScene

left to right direction

actor 管理者
actor スタッフ

frame スタジオ登録
note right of スタジオ登録
UC:
スタジオを登録する
end note

frame スタジオ削除
note right of スタジオ削除
UC:
* スタジオを特定する
* スタジオの内容を確認する
* スタジオを削除する

＜Note＞
* 予約されているスタジオを削除した場合は利用者に知らせる必要がある。
end note

frame スタジオ変更
note right of スタジオ変更
UC:
* スタジオを特定する
* スタジオの内容を確認する
* スタジオの内容を変更する
end note

frame スタジオ利用停止
note right of スタジオ利用停止
UC:
* スタジオを特定する
* スタジオの内容を確認する
* スタジオの利用を停止する

＜Note＞
* スタジオの故障や改装などで一時的に利用できなくなる場合などに
利用停止にすることでスタジオ予約できないようにする。
* 予約されているスタジオを利用停止にした場合は利用者に知らせる必要がある。
end note

管理者 -- スタジオ登録
管理者 -- スタジオ削除
管理者 -- スタジオ変更
管理者 -- スタジオ利用停止
スタッフ -- スタジオ利用停止

@enduml