@startuml UsageScene

left to right direction

actor 管理者
actor スタッフ

frame スタッフ登録
note right of スタッフ登録
UC:
スタッフアカウントを登録する
end note

frame スタッフ削除
note right of スタッフ削除
UC:
* スタッフアカウントを特定する
* スタッフアカウントの内容を確認する
* スタッフアカウントを削除する
end note

frame スタッフ変更
note right of スタッフ変更
UC:
* スタッフアカウントを特定する
* スタッフアカウントの内容を確認する
* スタッフアカウントを変更する

＜Note＞
スタッフが変更できる内容は限られる。
end note

管理者 -- スタッフ登録
管理者 -- スタッフ削除
管理者 -- スタッフ変更
スタッフ -- スタッフ変更

@enduml
