@startuml UsageScene

left to right direction

actor スタッフ

frame 会員確認
note right of 会員確認
UC:
* 会員アカウントを特定する
* 会員アカウントの内容を確認する

＜note＞
会員登録されているかどうかを確認する際などに利用する。
end note

frame 会員変更
note right of 会員変更
UC:
* 会員アカウントを特定する
* 会員アカウントの内容を確認する
* 会員アカウントを変更する

＜Note＞
基本的には会員以外が会員アカウントの情報を変更することがないが、
管理機能としては変更できる必要がある。
end note

frame 会員削除
note right of 会員削除
UC:
* 会員アカウントを特定する
* 会員アカウントの内容を確認する
* 会員アカウントを削除する

＜Note＞
基本的には会員以外が会員アカウントの情報を変更することがないが、
管理機能としては変更できる必要がある。
end note

スタッフ -- 会員確認
スタッフ -- 会員変更
スタッフ -- 会員削除

@enduml
