@startuml UsageScene

left to right direction

actor 管理者
actor スタッフ

frame 機材登録
note right of 機材登録
UC:
機材を登録する
end note

frame 機材変更
note right of 機材変更
UC:
* 機材を特定する
* 機材の内容を確認する
* 機材の内容を変更する
end note

frame 機材在庫管理
note right of 機材在庫管理
UC:
* 機材を特定する
* 機材の内容を確認する
* 機材の在庫を変更する

＜Note＞
* 機材を新規に入荷したり、故障により使えなくなった場合に在庫数を変更する。
* 予約されている機材の在庫数が減ることにより、機材が足りなくなってしまった場合は
利用者に知らせる必要がある。
end note

frame 機材削除
note right of 機材削除
UC:
* 機材を特定する
* 機材の内容を確認する
* 機材の在庫を削除する

＜Note＞
* 予約されている機材を削除した場合は利用者に知らせる必要がある。
end note

管理者 -- 機材登録
管理者 -- 機材変更
管理者 -- 機材在庫管理
管理者 -- 機材削除
スタッフ -- 機材登録
スタッフ -- 機材変更
スタッフ -- 機材在庫管理

@enduml
